hackmdPostgres:
  image: postgres
  environment:
    - POSTGRES_USER=hackmd
    - POSTGRES_PASSWORD=hackmdpass
    - POSTGRES_DB=hackmd
hackmd:
  image: manji-0/hackmd:latest
  environment:
    - POSTGRES_USER=hackmd
    - POSTGRES_PASSWORD=hackmdpass
  links:
    - hackmdPostgres
  ports:
    - "80:3000"
